In [1]:
import pandas as pd
import numpy as np

In [19]:
dataset=pd.read_csv("/content/Grocery Database.csv")
dataset

Flat no.      Name  No. of members  \
0         101     Anish               2   
1         102     Gupta               4   
2         103    Anisha               3   
3         104    Sanjay               5   
4         105  Pankhuri               3   
..        ...       ...             ...   
121      1201      Amit               2   
122      1202        Om               3   
123      1203     Jhamb               7   
124      1204     Kusum               5   
125      1210     Lucky               3   

     Amt of grocery purchased in a week(in kg)  Wholesale/Retail  
0                                            4                 1  
1                                            8                 0  
2                                            7                 1  
3                                           13                 0  
4                                            4                 1  
..                                         ...               ...  
121                                          3                 1  
122                                          3                 1  
123                                         20                 0  
124                                         18                 0  
125                                         10                 0  

[126 rows x 5 columns]

In [3]:
x=dataset.iloc[:,2:4].values
x

array([[ 2,  4],
       [ 4,  8],
       [ 3,  7],
       [ 5, 13],
       [ 3,  4],
       [ 1,  3],
       [ 2,  5],
       [ 3,  8],
       [ 4,  5],
       [ 4, 10],
       [ 3,  4],
       [ 2,  5],
       [ 3,  8],
       [ 4, 11],
       [ 3,  5],
       [ 2,  6],
       [ 4, 12],
       [ 2,  6],
       [ 5, 14],
       [ 3,  9],
       [ 1,  2],
       [ 3, 10],
       [ 4,  8],
       [ 2,  5],
       [ 4, 13],
       [ 3,  9],
       [ 3,  6],
       [ 5, 15],
       [ 3,  4],
       [ 4, 10],
       [ 5, 16],
       [ 2,  8],
       [ 2,  3],
       [ 4, 12],
       [ 2,  3],
       [ 4,  8],
       [ 3, 10],
       [ 2,  3],
       [ 5, 15],
       [ 1,  2],
       [ 3, 10],
       [ 3,  9],
       [ 3,  3],
       [ 3,  5],
       [ 2,  4],
       [ 4, 10],
       [ 2,  4],
       [ 3,  9],
       [ 2,  6],
       [ 4, 13],
       [ 4, 12],
       [ 4, 12],
       [ 2,  6],
       [ 5, 15],
       [ 4, 10],
       [ 3,  9],
       [ 5, 18],
       [ 5, 14],
       [ 3,  7

In [4]:
from sklearn import preprocessing
sc=preprocessing.StandardScaler()
z=sc.fit_transform(x)
z


array([[-1.01668045, -0.8604948 ],
       [ 0.62564951,  0.0392757 ],
       [-0.19551547, -0.18566693],
       [ 1.44681449,  1.16398882],
       [-0.19551547, -0.8604948 ],
       [-1.83784543, -1.08543742],
       [-1.01668045, -0.63555218],
       [-0.19551547,  0.0392757 ],
       [ 0.62564951, -0.63555218],
       [ 0.62564951,  0.48916094],
       [-0.19551547, -0.8604948 ],
       [-1.01668045, -0.63555218],
       [-0.19551547,  0.0392757 ],
       [ 0.62564951,  0.71410357],
       [-0.19551547, -0.63555218],
       [-1.01668045, -0.41060955],
       [ 0.62564951,  0.93904619],
       [-1.01668045, -0.41060955],
       [ 1.44681449,  1.38893144],
       [-0.19551547,  0.26421832],
       [-1.83784543, -1.31038005],
       [-0.19551547,  0.48916094],
       [ 0.62564951,  0.0392757 ],
       [-1.01668045, -0.63555218],
       [ 0.62564951,  1.16398882],
       [-0.19551547,  0.26421832],
       [-0.19551547, -0.41060955],
       [ 1.44681449,  1.61387406],
       [-0.19551547,

In [5]:
y=dataset.iloc[:,-1].values


In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)


In [7]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

  **KNN**

In [8]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [9]:
y_pred=classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


[[1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


In [10]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9375


**ANN**

In [11]:
import tensorflow as tf


In [12]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
ann.fit(x_train, y_train, batch_size = 25, epochs = 25)

Epoch 1/25
4/4 [==============================] - 1s 9ms/step - loss: 0.6109 - accuracy: 0.5532
Epoch 2/25
4/4 [==============================] - 0s 5ms/step - loss: 0.6037 - accuracy: 0.6809
Epoch 3/25
4/4 [==============================] - 0s 5ms/step - loss: 0.5970 - accuracy: 0.7340
Epoch 4/25
4/4 [==============================] - 0s 6ms/step - loss: 0.5903 - accuracy: 0.7660
Epoch 5/25
4/4 [==============================] - 0s 5ms/step - loss: 0.5831 - accuracy: 0.7766
Epoch 6/25
4/4 [==============================] - 0s 5ms/step - loss: 0.5764 - accuracy: 0.7766
Epoch 7/25
4/4 [==============================] - 0s 6ms/step - loss: 0.5698 - accuracy: 0.7766
Epoch 8/25
4/4 [==============================] - 0s 5ms/step - loss: 0.5631 - accuracy: 0.7766
Epoch 9/25
4/4 [==============================] - 0s 6ms/step - loss: 0.5572 - accuracy: 0.7766
Epoch 10/25
4/4 [==============================] - 0s 5ms/step - loss: 0.5504 - accuracy: 0.7766
Epoch 11/25
4/4 [======================

In [15]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

1/1 [==============================] - 0s 85ms/step
[[1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


In [16]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9375


**Logistic Regression**

In [17]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()
lg.fit(x_train,y_train)
y_pred = lg.predict(x_test)

In [18]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.875
